import { AlertCircle, ArrowRight, CalendarClock, CheckCircle2, FlaskConical, Users } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { api, formatDate } from '../api'
import { ErrorBox, Loading, PageHeader, StatusPill } from '../components'
import type { Milestone, Study } from '../types'

type DashboardData = { studies: Study[]; pending_events: number; upcoming_milestones: Milestone[] }
export default function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState('')
  useEffect(() => { api<DashboardData>('/dashboard').then(setData).catch(e => setError(e.message)) }, [])
  if (error) return <ErrorBox message={error} />; if (!data) return <Loading />
  const enrolled = data.studies.reduce((sum, s) => sum + s.enrolled_count, 0); const target = data.studies.reduce((sum, s) => sum + s.target_enrollment, 0)
  return <><PageHeader eyebrow="Trial operations" title="Good morning"><p>Monitor fictional studies, outstanding reviews, and operational milestones.</p></PageHeader><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<FlaskConical />} label="Active studies" value={data.studies.length} detail="All fictional" /><Metric icon={<Users />} label="Enrollment" value={`${enrolled}/${target}`} detail={`${Math.round(enrolled / target * 100)}% of target`} /><Metric icon={<AlertCircle />} label="Pending events" value={data.pending_events} detail="Awaiting PI review" attention /><Metric icon={<CalendarClock />} label="Open milestones" value={data.upcoming_milestones.length} detail="Upcoming or overdue" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">Study enrollment</h2><p className="mt-1 text-xs text-slate-500">Current database totals</p></div><Link to="/studies" className="text-sm font-semibold text-teal-700 hover:underline">View studies</Link></div><div className="divide-y divide-slate-100">{data.studies.map(s => { const pct = Math.round(s.enrolled_count / s.target_enrollment * 100); return <Link to={`/studies/${s.id}`} key={s.id} className="block p-5 transition hover:bg-slate-50"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-teal-700">{s.code}</p><h3 className="mt-1 font-semibold">{s.title}</h3></div><ArrowRight className="text-slate-400" size={18} /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{ width: `${pct}%` }} /></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{s.enrolled_count} enrolled</span><span>{pct}% of {s.target_enrollment}</span></div></Link> })}</div></section><section className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Milestones</h2><p className="mt-1 text-xs text-slate-500">Nearest operational dates</p></div><div className="divide-y divide-slate-100">{data.upcoming_milestones.map(m => <div key={m.id} className="flex gap-3 p-4"><div className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg ${m.status === 'overdue' ? 'bg-rose-50 text-rose-600' : 'bg-teal-50 text-teal-700'}`}>{m.status === 'overdue' ? <AlertCircle size={17} /> : <CheckCircle2 size={17} />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{m.title}</p><StatusPill value={m.status} /></div><p className="mt-1 text-xs text-slate-500">{m.study_code} · {formatDate(m.due_date)}</p></div></div>)}</div></section></div></>
}
function Metric({ icon, label, value, detail, attention = false }: { icon: ReactNode; label: string; value: string | number; detail: string; attention?: boolean }) { return <div className="card p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${attention ? 'bg-amber-50 text-amber-700' : 'bg-teal-50 text-teal-700'}`}>{icon}</div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div> }
