import { Activity, ArrowRight, FlaskConical } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../auth'

const demos = [{ label: 'Coordinator', username: 'coordinator', password: 'Coord@123' }, { label: 'PI', username: 'pi', password: 'PI@123' }, { label: 'Ethics Reviewer', username: 'ethics', password: 'Ethics@123' }]
export default function Login() {
  const { user, login } = useAuth(); const [username, setUsername] = useState('coordinator'); const [password, setPassword] = useState('Coord@123'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to="/" replace />
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); setBusy(true); try { await login(username, password) } catch (err) { setError(err instanceof Error ? err.message : 'Login failed') } finally { setBusy(false) } }
  return <main className="grid min-h-screen bg-white lg:grid-cols-[1.05fr_.95fr]"><section className="hidden bg-teal-900 p-14 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><Activity /></div><div><p className="font-bold">AarogyaTrial AI</p><p className="text-xs text-teal-100">Hackathon prototype</p></div></div><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-200">One accountable workflow</p><h1 className="mt-4 text-5xl font-bold leading-tight">From adverse-event report to human review.</h1><p className="mt-5 text-lg leading-relaxed text-teal-100">A focused demonstration of structured trial operations, transparent rules, and a visible decision history.</p></div><div className="flex items-center gap-2 text-sm text-teal-100"><FlaskConical size={18} /> Fictional data · Not for clinical use</div></section><section className="flex items-center justify-center bg-[#f8fbfa] p-5 sm:p-10"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3 text-teal-700"><Activity /><strong>AarogyaTrial AI</strong></div></div><p className="eyebrow">Secure demo access</p><h2 className="mt-2 text-3xl font-bold text-ink">Welcome back</h2><p className="mt-2 text-sm text-slate-600">Choose a demo role or enter its credentials.</p><div className="mt-6 grid grid-cols-3 gap-2">{demos.map(d => <button key={d.username} type="button" onClick={() => { setUsername(d.username); setPassword(d.password); setError('') }} className={`rounded-xl border px-2 py-2 text-xs font-semibold transition ${username === d.username ? 'border-teal-500 bg-teal-50 text-teal-700' : 'border-slate-200 bg-white text-slate-600 hover:border-teal-300'}`}>{d.label}</button>)}</div><form onSubmit={submit} className="card mt-4 space-y-5 p-6"><label className="block label">Username<input className="field" value={username} onChange={e => setUsername(e.target.value)} required autoComplete="username" /></label><label className="block label">Password<input className="field" type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<button disabled={busy} className="btn-primary w-full" type="submit">{busy ? 'Signing in…' : 'Sign in to demo'} <ArrowRight size={17} /></button></form><p className="mt-5 text-center text-xs leading-relaxed text-slate-500">This prototype uses fictional records and is not an approved clinical, regulatory, or medical coding system.</p></div></section></main>
}
