import { CheckCircle2, Info } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { ErrorBox, Loading, PageHeader } from '../components'
import type { AdverseEvent, Participant } from '../types'

export default function ReportEvent() {
  const [participants, setParticipants] = useState<Participant[]>([]); const [participant, setParticipant] = useState(''); const [narrative, setNarrative] = useState(''); const [onset, setOnset] = useState(''); const [severity, setSeverity] = useState('Mild'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [created, setCreated] = useState<AdverseEvent | null>(null)
  useEffect(() => { api<Participant[]>('/participants').then(items => { setParticipants(items); setParticipant(items[0]?.code || '') }).catch(e => setError(e.message)) }, [])
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); setBusy(true); try { const result = await api<AdverseEvent>('/adverse-events', { method: 'POST', body: JSON.stringify({ participant_code: participant, narrative, onset_date: onset, severity }) }); setCreated(result) } catch (e) { setError(e instanceof Error ? e.message : 'Could not save event') } finally { setBusy(false) } }
  if (!participants.length && !error) return <Loading />
  if (created) return <><PageHeader eyebrow="Event saved" title="Report sent for PI review" /><div className="card max-w-2xl p-6"><CheckCircle2 className="text-teal-600" size={36} /><h2 className="mt-4 text-lg font-bold">Adverse event #{created.id} is pending</h2><p className="mt-2 text-sm text-slate-600">The report was saved to the database. The suggestion remains provisional until a PI makes a decision.</p><div className="mt-5 rounded-xl bg-teal-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Demo suggestion · not official MedDRA coding</p><p className="mt-1 font-semibold">{created.suggested_category}</p><p className="mt-1 text-sm text-slate-600">{created.suggestion_reason}</p></div><div className="mt-6 flex flex-wrap gap-3"><button className="btn-primary" onClick={() => { setCreated(null); setNarrative(''); setOnset('') }}>Report another</button><Link className="btn-secondary" to="/audit">View audit history</Link></div></div></>
  return <><PageHeader eyebrow="Coordinator workflow" title="Report an adverse event"><p>Enter a fictional participant code and narrative. A simple keyword rule will offer a demo category; it will not become final without PI review.</p></PageHeader><div className="grid gap-6 xl:grid-cols-[1fr_.55fr]"><form onSubmit={submit} className="card space-y-5 p-6"><label className="block label">Fictional participant code<select className="field" value={participant} onChange={e => setParticipant(e.target.value)} required>{participants.map(p => <option key={p.code} value={p.code}>{p.code} · {p.study_code} / {p.site_code}</option>)}</select></label><label className="block label">Event narrative<textarea className="field min-h-36 resize-y" value={narrative} onChange={e => setNarrative(e.target.value)} minLength={12} maxLength={2000} required placeholder="Describe the fictional event, timing, and relevant observations…" /><span className="mt-1 block text-right text-xs font-normal text-slate-400">{narrative.length}/2000</span></label><div className="grid gap-5 sm:grid-cols-2"><label className="block label">Onset date<input className="field" type="date" value={onset} max={new Date().toISOString().slice(0, 10)} onChange={e => setOnset(e.target.value)} required /></label><label className="block label">Severity<select className="field" value={severity} onChange={e => setSeverity(e.target.value)}><option>Mild</option><option>Moderate</option><option>Severe</option></select></label></div>{error && <ErrorBox message={error} />}<button disabled={busy} className="btn-primary" type="submit">{busy ? 'Saving…' : 'Save and generate suggestion'}</button></form><aside className="card h-fit p-5"><div className="flex gap-3"><Info className="shrink-0 text-teal-600" size={20} /><div><h2 className="font-bold">What happens next?</h2><ol className="mt-3 space-y-3 text-sm leading-relaxed text-slate-600"><li><strong className="text-ink">1.</strong> The report is saved.</li><li><strong className="text-ink">2.</strong> Keyword rules suggest one clearly labeled demo category.</li><li><strong className="text-ink">3.</strong> A PI approves, corrects, or rejects it.</li><li><strong className="text-ink">4.</strong> Both actions appear in audit history.</li></ol></div></div></aside></div></>
}
