import { ArrowRight, MapPin, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, formatDate } from '../api'
import { ErrorBox, Loading, PageHeader, StatusPill } from '../components'
import type { Study, StudyDetail } from '../types'

export function Studies() {
  const [items, setItems] = useState<Study[]>([]); const [error, setError] = useState('')
  useEffect(() => { api<Study[]>('/studies').then(setItems).catch(e => setError(e.message)) }, [])
  if (error) return <ErrorBox message={error} />; if (!items.length) return <Loading />
  return <><PageHeader eyebrow="Portfolio" title="Fictional studies"><p>Enrollment and operational details for the two seeded Ayurveda trial demonstrations.</p></PageHeader><div className="grid gap-5 lg:grid-cols-2">{items.map(s => <Link key={s.id} to={`/studies/${s.id}`} className="card group p-6 transition hover:-translate-y-0.5 hover:border-teal-300"><div className="flex justify-between"><div><p className="eyebrow">{s.code}</p><h2 className="mt-2 text-xl font-bold">{s.title}</h2></div><ArrowRight className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-teal-600" /></div><p className="mt-3 text-sm leading-relaxed text-slate-600">{s.description}</p><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-500" style={{ width: `${s.enrolled_count / s.target_enrollment * 100}%` }} /></div><div className="mt-3 flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-slate-600"><Users size={16} /> {s.enrolled_count} of {s.target_enrollment}</span><StatusPill value={s.status} /></div></Link>)}</div></>
}
export function StudyDetails() {
  const { id } = useParams(); const [study, setStudy] = useState<StudyDetail | null>(null); const [error, setError] = useState('')
  useEffect(() => { api<StudyDetail>(`/studies/${id}`).then(setStudy).catch(e => setError(e.message)) }, [id])
  if (error) return <ErrorBox message={error} />; if (!study) return <Loading />
  return <><PageHeader eyebrow={study.code} title={study.title}><p>{study.description}</p></PageHeader><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Study sites</h2><p className="mt-1 text-xs text-slate-500">Enrollment target, current count, and plan-to-date</p></div><div className="divide-y">{study.sites.map(site => <div key={site.id} className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-semibold">{site.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13} /> {site.code} · {site.city}</p></div><div className="text-sm sm:text-right"><p><strong>{site.enrolled_count}</strong> / {site.target_enrollment} enrolled</p><p className={`mt-1 text-xs ${site.enrolled_count < site.planned_to_date ? 'text-amber-700' : 'text-teal-700'}`}>{site.planned_to_date} planned to date</p></div></div></div>)}</div></section><section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Coded participants</h2><p className="mt-1 text-xs text-slate-500">No real names or personal identifiers</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Participant code</th><th className="px-5 py-3">Site</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y">{study.participants.map(p => <tr key={p.code}><td className="px-5 py-3 font-mono font-semibold">{p.code}</td><td className="px-5 py-3">{p.site_code}</td><td className="px-5 py-3"><StatusPill value={p.status} /></td></tr>)}</tbody></table></div></section></div><section className="card h-fit overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Milestones</h2></div><div className="divide-y">{study.milestones.map(m => <div key={m.id} className="p-5"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold">{m.title}</p><StatusPill value={m.status} /></div><p className="mt-2 text-xs text-slate-500">Due {formatDate(m.due_date)}</p></div>)}</div></section></div></>
}
