import { Activity, AlertTriangle, BookOpenCheck, ClipboardPlus, FileClock, Gauge, LogOut, Menu, ShieldCheck, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { NavLink, Navigate, Outlet } from 'react-router-dom'
import { useAuth } from './auth'
import type { Role } from './types'

const navItems = [{ to: '/', label: 'Overview', icon: Gauge }, { to: '/studies', label: 'Studies', icon: BookOpenCheck }, { to: '/report-event', label: 'Report event', icon: ClipboardPlus, roles: ['coordinator'] }, { to: '/review', label: 'PI review', icon: ShieldCheck, roles: ['pi'] }, { to: '/risks', label: 'Risk rules', icon: AlertTriangle }, { to: '/audit', label: 'Audit history', icon: FileClock }]
export function Layout() {
  const { user, logout } = useAuth(); const [open, setOpen] = useState(false)
  if (!user) return <Navigate to="/login" replace />
  const roleLabel = { coordinator: 'Coordinator', pi: 'Principal Investigator', ethics_reviewer: 'Ethics Reviewer' }[user.role]
  return <div className="min-h-screen bg-[#f5f8f7]"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur lg:hidden"><div className="flex h-16 items-center justify-between px-4"><Brand compact /><button aria-label="Toggle navigation" onClick={() => setOpen(!open)} className="rounded-lg p-2">{open ? <X /> : <Menu />}</button></div></header>{open && <button className="fixed inset-0 z-30 bg-slate-900/30 lg:hidden" aria-label="Close navigation" onClick={() => setOpen(false)} />}<aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-slate-200 bg-white p-5 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><Brand /><div className="mt-7 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs leading-relaxed text-amber-900"><strong>Hackathon demo</strong><br />Fictional data only. Not approved for clinical use.</div><nav className="mt-6 flex-1 space-y-1">{navItems.filter(item => !item.roles || item.roles.includes(user.role)).map(item => <NavLink key={item.to} to={item.to} end={item.to === '/'} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive ? 'bg-teal-50 text-teal-700' : 'text-slate-600 hover:bg-slate-50 hover:text-ink'}`}><item.icon size={18} />{item.label}</NavLink>)}</nav><div className="border-t border-slate-200 pt-4"><p className="font-semibold text-ink">{user.display_name}</p><p className="text-xs text-slate-500">{roleLabel}</p><button onClick={logout} className="mt-3 flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-rose-600"><LogOut size={16} /> Sign out</button></div></aside><main className="lg:pl-72"><div className="mx-auto max-w-7xl p-4 sm:p-7 lg:p-10"><Outlet /></div></main></div>
}
function Brand({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-teal-600 text-white"><Activity size={22} /></div><div><p className="font-bold tracking-tight text-ink">AarogyaTrial AI</p>{!compact && <p className="text-xs text-slate-500">Ayurveda trial workspace</p>}</div></div> }
export function PageHeader({ eyebrow, title, children, action }: { eyebrow: string; title: string; children?: ReactNode; action?: ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-ink sm:text-3xl">{title}</h1>{children && <div className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">{children}</div>}</div>{action}</div> }
export function Loading() { return <div className="grid min-h-[40vh] place-items-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-teal-100 border-t-teal-600" aria-label="Loading" /></div> }
export function ErrorBox({ message }: { message: string }) { return <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{message}</div> }
export function StatusPill({ value }: { value: string }) { const lowered = value.toLowerCase(); const color = lowered === 'pending' || lowered === 'upcoming' || lowered === 'moderate' ? 'bg-amber-100 text-amber-800' : lowered === 'rejected' || lowered === 'overdue' || lowered === 'severe' ? 'bg-rose-100 text-rose-800' : 'bg-teal-100 text-teal-800'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold capitalize ${color}`}>{value.replace('_', ' ')}</span> }
export function RoleGate({ roles, children }: { roles: Role[]; children: ReactNode }) { const { user } = useAuth(); return user && roles.includes(user.role) ? children : <Navigate to="/" replace /> }
